# parameters

## SERVO NUMBER INDEX
SERVO_BOTTOM = 0
SERVO_LEFT = 1
SERVO_RIGHT = 2
SERVO_HAND = 3

## CALIBRATION FLAG
CONFIRM_FLAG = 0x80
CALIBRATION_FLAG = 10
CALIBRATION_LINEAR_FLAG = 11
CALIBRATION_SERVO_FLAG = 12
CALIBRATION_STRETCH_FLAG = 13

## OFFSET EEPROM ADDRESS
LINEAR_INTERCEPT_START_ADDRESS = 70
LINEAR_SLOPE_START_ADDRESS = 50
OFFSET_START_ADDRESS = 30
OFFSET_STRETCH_START_ADDRESS = 20

SERIAL_NUMBER_ADDRESS = 100

## EEPROM DATA TYPE INDEX
EEPROM_DATA_TYPE_BYTE = 1
EEPROM_DATA_TYPE_INTEGER = 2
EEPROM_DATA_TYPE_FLOAT = 4

## PROTOCOL MESSAGE
# READY & Response
READY                   = "@1"
OK                      = "OK"
# Set Command
SET_POSITION            = "G0 X{} Y{} Z{} F{}"
SET_POSITION_RELATIVE   = "G2204 X{} Y{} Z{} F{}"
SET_SERVO_ANGLE         = "G2202 N{} V{}"
STOP_MOVING             = "G2203"
SET_PUMP                = "M2231 V{}"
GET_PUMP                = "P2231"
SET_GRIPPER             = "M2232 V{}"
SET_BUZZER              = "M2210 F{} T{}"
SET_POLAR               = "G2201 S{} R{} H{} F{}"
ATTACH_SERVO            = "M2201 N{}"
DETACH_SERVO            = "M2202 N{}"
# Get Command
GET_SIMULATION          = "M2222 X{} Y{} Z{} P0"
GET_FIRMWARE_VERSION    = "P2203"
GET_HARDWARE_VERSION    = "P2202"
GET_COOR                = "P2220"
GET_SERVO_ANGLE         = "P2200"
GET_IS_MOVE             = "M2200"
GET_TIP_SENSOR          = "P2233"
GET_POLAR               = "P2221"
GET_GRIPPER             = "P2232"
GET_EEPROM              = "M2211 N0 A{} T{}"
SET_EEPROM              = "M2212 N0 A{} T{} V{}"
GET_ANALOG              = "P2241 N{}"
GET_DIGITAL             = "P2240 N{}"

# Report Command
SET_REPORT_POSITION     = "M120 V{}"
REPORT_POSITION_PREFIX  = "@3"

# Protocol Select
SET_PROTOCOL = "FOO"
